### ISSUE TITLE
from storage.blob import BlockBlobService ModuleNotFoundError: No module named 'storage'

### ISSUE THREAD

**Issue by AndresUrregoAngel** [Azure-Samples/azure-sdk-for-python-storage-blob-upload-download#10]
I'm working on python version 3.7.1 and I have already installed the suggested packages:

```
MacBook-Pro:Downloads $ pip3 freeze | grep azure
azure-common==1.1.17
azure-nspkg==3.0.2
azure-storage==0.36.0
azure-storage-blob==1.4.0
azure-storage-common==1.4.0
```

However, when I try the import `from storage.blob import BlockBlobService`  I get this weird error about no module called **AZURE**

**Comment by jongio** [comment]
This should be resolved.  Please reopen if you are able to reproduce.  Thanks
