### ISSUE TITLE
Create large blob

### ISSUE THREAD

**Issue by damianw2** [Azure-Samples/azure-sdk-for-python-storage-blob-upload-download#12]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [X] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> Use 'create_blob_from_path' with file more than 100Mb

### Any log messages given by the failure
> No error logs

### Expected/desired behavior
> Blob to be created

### OS and Version?
> Linux Ubuntu 18.04

### Versions
>

### Mention any other details that might be useful
To solve issue, max_connection=1 must be added as a parameter. 
> ---------------------------------------------------------------

**Comment by jongio** [comment]
We're closing this since it only applies to v11, please use v12, which shouldn't have this issue.  Thanks
