### ISSUE TITLE
API list for Phython SDK

### ISSUE THREAD

**Issue by nesalang** [Azure-Samples/azure-sdk-for-python-storage-blob-upload-download#14]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [x] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
> I can't find documentation on python sdk's APIs

### Any log messages given by the failure
> n/a

### Expected/desired behavior
> having list of API supported by python SDK would increase the productivity.

### OS and Version?
> n/a

### Versions
> n/a

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.

**Comment by jongio** [comment]
Here's the Python SDK reference https://azure.github.io/azure-sdk-for-python/

**Comment by nesalang** [comment]
> Here's the Python SDK reference https://azure.github.io/azure-sdk-for-python/

thanks
