### ISSUE TITLE
Incorrect padding

### ISSUE THREAD

**Issue by jatin7gupta** [Azure-Samples/azure-sdk-for-python-storage-blob-upload-download#17]
> Please provide us with the following information:
> ---------------------------------------------------------------

### This issue is for a: (mark with an `x`)
```
- [x] bug report -> please search issues before submitting
- [ ] feature request
- [ ] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```

### Minimal steps to reproduce
>git clone
python example.py

### Any log messages given by the failure
>None

### Expected/desired behavior
>Run or error

### OS and Version?
> Windows 7, 8 or 10. Linux (which distribution). macOS (Yosemite? El Capitan? Sierra?)
Windows 10
### Versions
>8/11/2019 date which ever version is active

### Mention any other details that might be useful

> ---------------------------------------------------------------
> Thanks! We'll be in touch soon.
![Annotation 2019-11-08 125137](https://user-images.githubusercontent.com/9363287/68442890-86b14a00-0226-11ea-8fb6-3f9f702952f1.png)

**Comment by jongio** [comment]
This should be resolved.  Please reopen if you are able to reproduce.  Thanks
